version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-dogs-java
    tty: true
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - my-network

  db:
      image: mysql:8.0
      container_name: nexus-dogs-mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - '3306:3306'
      volumes:
        - mysql_volume:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - my-network

volumes:
  mysql_volume:

networks:
  my-network: